### ISSUE TITLE
Write Rationale in README

### ISSUE THREAD

**Issue by deadghost** [funcool/buddy#28]
In clojure tradition, there's often a section titled `Rationale` explaining your motivation for creating something. In this case, as a potential user I wonder why you wrote this when Friend is the current de facto auth library. I also want to know what the benefits and drawbacks of Buddy are compared to Friend.

After digging around, I found some compelling reasons to use Buddy and it would help others in the future to list these upfront in the README.

**Comment by niwibe** [comment]
You are right, a good rationale would be awesome. Thank you for you suggestion.

In any case the rationale will be on buddy-auth instead of on buddy documentation. The `buddy` repository and package is simple meta-package that encapsulates different modules that can be used separately. 

I'll keep this issue open until the task is done. Thanks again!

**Comment by niwinz** [comment]
I think I will not going to do it on the end, so I close this issue.
